### ISSUE TITLE
Cute cat please

### ISSUE THREAD

**Issue by hoanglethanhson** [ggerganov/morse-meme#1]
nice demo app, but can you change the pic of the cat to a cute one? I think the black cat with white eyes speaking Morse code is a little bit scary? Thank you for reading :D

**Comment by hoanglethanhson** [comment]
I suggest using Cheems Shiba dog if you want to make a change =))

**Comment by ggerganov** [comment]
Added Shiba Inu:

https://user-images.githubusercontent.com/1991296/128639139-2b246c43-464f-4493-9222-da89b94353c8.mp4

Will add more options in the future.
